cloud:
  aws:
    credentials:
      access-key: AKIA3FLD22INBIWAJPNV
      secret-key: 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
    region:
      static: ap-southeast-2
    stack:
      auto: false

application:
  bucket:
    name: javaviggastorage2


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

#server:
#  port: 9090
